### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by luckylittle** [hashworks/srrdb-Terminal-Client#1]
I cannot use the binary - the error is:
`./srrdb: /lib64/libc.so.6: version GLIBC_2.32 not found (required by ./srrdb)`

Problem: Seems like it is just a problem of using CGO when the C library you have under the hood is not compatible with `glibc 2.32` or there is no C library but you are trying to build with CGO, therefore, it can not detect/find the correct version for `.so` files.

Solution: `CGO_ENABLED=1` should never be used and it should be avoided as much as possible when building the binaries.

**Comment by hashworks** [comment]
Thanks, please test [v1.2.0](https://github.com/hashworks/srrdb-Terminal-Client/releases/tag/v1.2.0)

**Comment by hashworks** [comment]
```
$ ldd ./srrdb
	not a dynamic executable
```

**Comment by luckylittle** [comment]
I have built it myself without CGO and it works fine. Keep doing a great job!
